name: Pull request
description: Change something
assignees:
  - janoszen
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to this repository! Please fill out the following two questions.
  - type: textarea
    id: change
    attributes:
      label: What did you change?
      description: Please describe the change you are making and why.
      placeholder: I am adding...
      value: ""
    validations:
      required: true
  - type: input
    id: license
    attributes:
      label: License
      description: I dedicate any and all copyright interest in this software to the public domain. I make this dedication for the benefit of the public at large and to the detriment of my heirs and successors. I intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.
      placeholder: Your name or GitHub alias here
    validations:
      required: true
